/* ===== 生图 ===== */
function getImgModels(){let l=null;try{l=JSON.parse(localStorage.getItem('img_model_list'));}catch(e){}if(!Array.isArray(l)){l=['gemini-3.1-flash-image-preview','Kwai-Kolors/Kolors'];localStorage.setItem('img_model_list',JSON.stringify(l));}return l;}
function saveImgModels(l){localStorage.setItem('img_model_list',JSON.stringify(l));}
function selectImgModel(m){localStorage.setItem('img_model',m);}
function editImgModel(i,v){const l=getImgModels();const old=l[i];l[i]=v.trim()||old;saveImgModels(l);if(localStorage.getItem('img_model')===old)localStorage.setItem('img_model',l[i]);}
function delImgModel(i){const l=getImgModels();const rm=l[i];l.splice(i,1);saveImgModels(l);if(localStorage.getItem('img_model')===rm)localStorage.setItem('img_model',l[0]||'');renderImageSettings();}
function addImgModelRow(){const l=getImgModels();l.push('新模型');saveImgModels(l);renderImageSettings();}
function resLabel(px){const p=parseInt(px);if(p<=1024)return '1K';if(p<=2048)return '2K';if(p<=4096)return '4K';return p+'px';}
function getImgResList(){let l=null;try{l=JSON.parse(localStorage.getItem('img_res_list'));}catch(e){}if(!Array.isArray(l)){l=['1024','2048','4096'];localStorage.setItem('img_res_list',JSON.stringify(l));}return l;}
function saveImgResList(l){localStorage.setItem('img_res_list',JSON.stringify(l));}
function selectImgRes(px){localStorage.setItem('img_res',px);}
function editImgRes(i,v){const l=getImgResList();const old=l[i];const nv=String(parseInt(v)||old);l[i]=nv;saveImgResList(l);if(localStorage.getItem('img_res')===old)localStorage.setItem('img_res',nv);renderImageSettings();}
function delImgRes(i){const l=getImgResList();const rm=l[i];l.splice(i,1);saveImgResList(l);if(localStorage.getItem('img_res')===rm)localStorage.setItem('img_res',l[0]||'1024');renderImageSettings();}
function addImgResRow(){const v=prompt('输入分辨率长边像素（如 1024=1K, 2048=2K, 4096=4K）','1536');if(!v)return;const l=getImgResList();l.push(String(parseInt(v)||1024));saveImgResList(l);renderImageSettings();}
function toggleImgEnabled(on){setBool('img_enabled',on);renderGenImgMenu();}
function renderGenImgMenu(){document.getElementById('genImgMenuBtn').style.display=imgEnabled()?'block':'none';}

function openImgGen(){document.getElementById('actionMenu').classList.remove('show');if(!imgEnabled()){showToast('🎨 生图已关闭，请在生图设置开启');return;}const mode=localStorage.getItem('img_gen_mode')||'free';const hint={free:'当前：免费 Pollinations（无需Key，建议英文）',gemini:'当前：Gemini 原生，支持图生图',openai:'当前：OpenAI 图像端点',chat:'当前：Chat 多模态，支持图生图'}[mode];document.getElementById('imgGenModeHint').textContent=hint;clearGenInit();document.getElementById('imgGenPrompt').value='';document.getElementById('imgGenPanel').classList.add('show');}
function handleGenInit(input){const f=input.files[0];if(!f)return;const r=new FileReader();r.onload=e=>{pendingGenInit=e.target.result;document.getElementById('imgInitThumb').src=pendingGenInit;document.getElementById('imgInitPrev').classList.add('show');};r.readAsDataURL(f);input.value='';}
function clearGenInit(){pendingGenInit=null;document.getElementById('imgInitPrev').classList.remove('show');document.getElementById('imgInitThumb').src='';}
async function runImgGen(){const promptText=document.getElementById('imgGenPrompt').value.trim();if(!promptText){showToast('请输入描述');return;}const initImg=pendingGenInit;document.getElementById('imgGenPanel').classList.remove('show');const mode=localStorage.getItem('img_gen_mode')||'free';addMessage('user','🎨 '+promptText+(initImg?'（图生图）':''));if(initImg){const uid=genUid();const ts=Date.now();conversationHistory.push({role:'user',content:'[原图]',image:initImg,uid,ts});renderImageMessage('user',initImg,uid,ts);saveHistory();}const loading=addLoadingDOM();try{let imgUrl=null;const{w,h}=getImgWH();
    if(mode==='free'){imgUrl=`https://image.pollinations.ai/prompt/${encodeURIComponent(promptText)}?width=${w}&height=${h}&nologo=true&seed=${Date.now()}`;await new Promise((res,rej)=>{const im=new Image();im.onload=res;im.onerror=()=>rej(new Error('免费图片加载失败'));im.src=imgUrl;});}
    else{const url=(localStorage.getItem('img_url')||'').trim();const key=(localStorage.getItem('img_key')||'').trim();const model=(localStorage.getItem('img_model')||getImgModels()[0]||'').trim();if(!key){loading.remove();alert('请先在「生图设置」填入收费 API Key');openSettings();settingsMode='image';renderProviderList();renderImageSettings();return;}const base=url.replace(/\/+$/,'');
        if(mode==='gemini'){const gurl=`${base}/v1beta/models/${model}:generateContent`;const parts=[{text:promptText}];if(initImg){const b64=initImg.split(',')[1];const mt=(initImg.match(/^data:(.*?);/)||[])[1]||'image/png';parts.push({inline_data:{mime_type:mt,data:b64}});}const r=await fetch(gurl,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${key}`},body:JSON.stringify({contents:[{parts}]})});if(!r.ok){const t=await r.text();throw new Error(`Gemini生图(${r.status}) ${t.slice(0,120)}`);}const d=await r.json();const ps=d.candidates?.[0]?.content?.parts||[];for(const p of ps){const id=p.inlineData||p.inline_data;if(id&&id.data){imgUrl='data:'+(id.mimeType||id.mime_type||'image/png')+';base64,'+id.data;break;}}if(!imgUrl)throw new Error('Gemini未返回图片');}
        else if(mode==='openai'){const ourl=base.includes('/images/generations')?base:base+'/v1/images/generations';const r=await fetch(ourl,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${key}`},body:JSON.stringify({model,prompt:promptText,image_size:`${w}x${h}`,n:1})});if(!r.ok){const t=await r.text();throw new Error(`OpenAI生图(${r.status}) ${t.slice(0,120)}`);}const d=await r.json();imgUrl=d.data?.[0]?.url||(d.data?.[0]?.b64_json&&('data:image/png;base64,'+d.data[0].b64_json))||d.images?.[0]?.url;if(!imgUrl)throw new Error('OpenAI未返回图片');}
        else if(mode==='chat'){const curl=base.includes('/chat/completions')?base:base+'/v1/chat/completions';const content=[{type:'text',text:'生成图片：'+promptText}];if(initImg)content.push({type:'image_url',image_url:{url:initImg}});const r=await fetch(curl,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${key}`},body:JSON.stringify({model,messages:[{role:'user',content}]})});if(!r.ok){const t=await r.text();throw new Error(`Chat生图(${r.status}) ${t.slice(0,120)}`);}const d=await r.json();const msg=d.choices?.[0]?.message;imgUrl=msg?.images?.[0]?.url||msg?.images?.[0]?.image_url?.url;if(!imgUrl&&msg?.content){const md=(typeof msg.content==='string'?msg.content:'').match(/!\[.*?\]\((.*?)\)|(https?:\/\/\S+\.(?:png|jpg|jpeg|webp))|(data:image\/[^)\s]+)/i);if(md)imgUrl=md[1]||md[2]||md[3];}if(!imgUrl)throw new Error('Chat模式未返回图片，请改用 Gemini/OpenAI 模式');}
    }
    loading.remove();const uid=genUid();const ts=Date.now();conversationHistory.push({role:'assistant',content:'[图片] '+promptText,image:imgUrl,uid,ts});renderImageMessage('assistant',imgUrl,uid,ts);saveHistory();clearGenInit();
}catch(e){loading.remove();addMessage('assistant','❌ '+e.message,genUid());}}
